import { createHmac, timingSafeEqual } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir, rm, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";

import { env } from "@/lib/env";
import type { StorageDriver } from "@/lib/storage/types";

/**
 * Filesystem driver for development.
 *
 * It exists so the whole product — guest upload, quota rejection, gallery,
 * ZIP download, retention deletion — can be exercised end to end without an
 * AWS account. It deliberately mirrors the S3 contract rather than shortcutting
 * it: uploads go to a signed, expiring, size-limited endpoint, and reads of
 * originals are signed too. If it worked here but not on S3 the driver would be
 * worthless as a development target.
 */

const ROOT = path.join(process.cwd(), ".storage");

function secret(): string {
  return (
    process.env.LOCAL_STORAGE_SECRET ??
    process.env.SUPABASE_SECRET_KEY ??
    process.env.SUPABASE_SERVICE_ROLE_KEY ??
    "say-cheese-development-secret"
  );
}

export function signLocal(parts: string[]): string {
  return createHmac("sha256", secret()).update(parts.join("\n")).digest("hex");
}

export function verifyLocal(parts: string[], signature: string): boolean {
  const expected = Buffer.from(signLocal(parts));
  const given = Buffer.from(signature);
  return expected.length === given.length && timingSafeEqual(expected, given);
}

/** Keys are generated by us, but this endpoint is reachable, so check anyway. */
export function safeKey(key: string): string {
  const normalised = path.posix.normalize(key);
  if (
    normalised.startsWith("/") ||
    normalised.startsWith("..") ||
    normalised.includes("../")
  ) {
    throw new Error("Invalid storage key");
  }
  return normalised;
}

export function localPath(key: string): string {
  return path.join(ROOT, safeKey(key));
}

async function ensureDir(filePath: string) {
  await mkdir(path.dirname(filePath), { recursive: true });
}

export const localDriver: StorageDriver = {
  name: "local",

  async presignUpload({ key, contentType, maxBytes, expiresInSeconds = 900 }) {
    const exp = String(Math.floor(Date.now() / 1000) + expiresInSeconds);
    const max = String(maxBytes);
    const sig = signLocal(["put", key, exp, max, contentType]);

    return {
      url: `${env.siteUrl.replace(/\/$/, "")}/api/storage/local`,
      fields: { key, exp, max, "Content-Type": contentType, sig },
      fileField: "file",
    };
  },

  async presignDownload({ key, expiresInSeconds = 300, downloadName }) {
    const exp = String(Math.floor(Date.now() / 1000) + expiresInSeconds);
    const name = downloadName ?? "";
    const sig = signLocal(["get", key, exp, name]);
    const params = new URLSearchParams({ key, exp, sig });
    if (name) params.set("name", name);
    return `${env.siteUrl.replace(/\/$/, "")}/api/storage/local?${params}`;
  },

  publicUrl(key) {
    // No CDN in development. Thumbnails are served by the app, which is fine
    // at development volumes and would not be in production.
    return `${env.siteUrl.replace(/\/$/, "")}/api/media/${key}`;
  },

  async put({ key, body }) {
    const file = localPath(key);
    await ensureDir(file);
    if (Buffer.isBuffer(body)) {
      await writeFile(file, body);
    } else {
      const { createWriteStream } = await import("node:fs");
      await pipeline(body, createWriteStream(file));
    }
  },

  async getStream(key) {
    return createReadStream(localPath(key)) as unknown as Readable;
  },

  async head(key) {
    try {
      const s = await stat(localPath(key));
      return { size: s.size };
    } catch {
      return null;
    }
  },

  async remove(keys) {
    await Promise.all(
      keys.map((key) => rm(localPath(key), { force: true }).catch(() => {})),
    );
  },

  async removePrefix(prefix) {
    const dir = localPath(prefix);
    let count = 0;
    try {
      const entries = await readdir(dir, {
        recursive: true,
        withFileTypes: true,
      });
      count = entries.filter((e) => e.isFile()).length;
    } catch {
      return 0;
    }
    await rm(dir, { recursive: true, force: true });
    return count;
  },
};
